ecommerceStore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('category-list', views.category_list, name='category-list'),
    path('brand-list', views.brand_list, name='brand-list'),
    path('product-list', views.product_list, name='product-list'),
    path('category-product-list/<int:category_id>', views.category_product_list, name='category-product-list'),
    path('brand-product-list/<int:brand_id>', views.brand_product_list, name='brand-product-list'),
    path('product/<str:slug>/<int:id>', views.product_detail, name='product-detail'),
    path('filter-data', views.filter_data, name='filter-data'),
    path('load-more-data', views.load_more_data, name='load-more-data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe

class Banner(models.Model):
    img = models.ImageField(upload_to='static/banner_imgs/')
    alt_text = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = "7. Banners"

class Category(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="static/cat_imgs/")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "1. Categories"

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))



class Brand(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="static/brand_imgs/")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "2. Brands"

class Color(models.Model):
    title = models.CharField(max_length=50)
    color_code = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def color_display(self):
        return mark_safe('<div style="width:50px; height:50px; background:%s" />' % (self.color_code))

    class Meta:
        verbose_name_plural = "4. Colors"

class Size(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "5. Sizes"

class Product(models.Model):
    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=400)
    detail = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "3. Products"

class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.PositiveBigIntegerField()
    image = models.ImageField(upload_to="static/product_imgs/", null=True)

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name_plural = "6. ProductAttributes"
    

main/views.py
from turtle import title
from django.http import JsonResponse
from django.shortcuts import render
from .models import Brand, Category, Product, ProductAttribute, Banner
from django.template.loader import render_to_string

def home(request):
    banners = Banner.objects.all().order_by('-id')
    featured_products = Product.objects.filter(is_featured=True).order_by('-id')
    return render(request, 'index.html', {'featured_products': featured_products, 'banners': banners})

def category_list(request):
    categories = Category.objects.all().order_by('-id')
    return render(request, 'category_list.html', {'categories': categories})

def brand_list(request):
    brands = Brand.objects.all().order_by('-id')
    return render(request, 'brand_list.html', {'brands': brands})

def product_list(request):
    total_products = Product.objects.count()
    products = Product.objects.all().order_by('-id')[:2]

    return render(request, 'product_list.html', 
        {
            'total_products':total_products,
            'products': products, 
        }
    )

def category_product_list(request, category_id):
    category = Category.objects.get(id=category_id)
    category_products = Product.objects.filter(category=category).order_by('-id')

    return render(request, 'category_product_list.html', {
        'category': category,
        'category_products': category_products, 
    })

def brand_product_list(request, brand_id):
    brand = Brand.objects.get(id=brand_id)
    brand_products = Product.objects.filter(brand=brand).order_by('-id')

    return render(request, 'brand_product_list.html', {
        'brand': brand,
        'brand_products': brand_products, 
    })

def product_detail(request, slug, id):
    product_detail = Product.objects.get(id=id)
    related_products = Product.objects.filter(category=product_detail.category).exclude(id=id)[:4]
    colors = ProductAttribute.objects.filter(product=product_detail).values('color__id', 'color__title', 'color__color_code', 'price').distinct()
    sizes = ProductAttribute.objects.filter(product=product_detail).values('size__id', 'size__title', 'price', 'color__id').distinct()
    return render(request, 'product_detail.html', {'product_detail': product_detail, 'related_products': related_products, 'colors':colors, 'sizes':sizes})

def search(request):
    q = request.GET['q']
    featured_products = Product.objects.filter(title__contains=q).order_by('-id')
    return render(request, 'search.html', {'featured_products': featured_products})

def filter_data(request):
    colors=request.GET.getlist('color[]')
    categories=request.GET.getlist('color[]')
    brands=request.GET.getlist('color[]')
    sizes=request.GET.getlist('color[]')
    allProducts = Product.objects.all()
    t=render_to_string('ajax/product-list', {'data':allProducts})
    return JsonResponse({'data': t})

def load_more_data(request):
    offset = int(request.GET['offset'])
    limit = int(request.GET['limit'])
    products = Product.objects.all().order_by('-id')[offset:offset+limit]

    t=render_to_string('ajax/product-list.html', {'products':products})
    return JsonResponse({'data': t})

main/templates/ajax/product-list.html
{% for product in products%}
				<div class="col-md-4 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="#">{{product.title}}</a></h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
{% endfor %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Ecommerce Bootstrap Template</title>
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<!-- Bootstrap 4 JS -->
    <script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
    <!--CustomeJS-->
    <script type="text/javascript" src="{% static 'custom.js' %}"></script>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="{% url 'home' %}">Sneaker Heads</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
            <form class="form-inline my-2 my-lg-0" action="/search">
                <div class="input-group mb-3">
                    <input name="q" type="text" class="form-control" placeholder="search" />
                    <div class="input-group-append">
                      <button class="btn btn-dark" type="submit" id="button-addon2">Search</button>
                    </div>
                </div>
            </form>
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="<?php echo $baseUrl; ?>">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'category-list' %}">Categories</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'brand-list' %}">Brands</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="<?php echo $baseUrl; ?>/cart.php"><i class="fa fa-shopping-cart"></i> Cart (2)</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="<?php echo $baseUrl; ?>/account.php"><i class="fa fa-user"></i> My Account</a>
		      </li>
		    </ul>
		  </div>
		</div>
	</nav>

    {% block content %}
    {% endblock content %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top container">
        <div class="row">
          <div class="col-12 col-md">
            <a href="#">Bottle Shop</a>
            <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Cool stuff</a></li>
              <li><a class="text-muted" href="#">Random feature</a></li>
              <li><a class="text-muted" href="#">Team feature</a></li>
              <li><a class="text-muted" href="#">Stuff for developers</a></li>
              <li><a class="text-muted" href="#">Another one</a></li>
              <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </body>
    </html>

main/templates/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Brands</h3>
	<div class="row">
		{% if brands %}
			{% for brand in brands %}
				<div class="col-md-3 mb-4">
					<div class="card shadow">
					<a href="brand-product-list/{{brand.id}}"><img src="/media/{{brand.image}}" class="card-img-top" alt="{{brand.title}}"></a>
					<div class="card-body">
						<h6 class="card-text"><a href="#">{{brand.title}}</a></h6>
					</div>
					</div>
				</div>
		{% endfor %}
	{% endif %}
	</div>
</main>
{% endblock %}

main/templates/brand_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		{% comment %} <div class="col-md-3">
			{% include 'filters.html' %}
		</div> {% endcomment %}
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
            {% if brand_products %}
			<div class="row">
                {% for brand_product in brand_products %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{brand_product.slug}}/{{brand_product.id}}"><img src="/media/{{brand_product.productattribute_set.first.image}}" class="card-img-top" alt="{{brand_product.title}}"></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="#">{{brand_product.title}}</a></h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
            {% endif %}
			<p class="my-4 text-center"><a href="/products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

main/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Categories</h3>
	<div class="row">
		{% if categories %}
			{% for category in categories %}
				<div class="col-md-3 mb-4">
					<div class="card shadow" >
					<a href="/category-product-list/{{category.id}}"><img src="/media/{{category.image}}" class="card-img-top" alt="{{category.title}}"></a>
					<div class="card-body"">
						<h6 class="card-text"><a href="#">{{category.title}}</a></h6>
					</div>
					</div>
				</div>
		{% endfor %}
	{% endif %}
	</div>
</main>
{% endblock %}

main/templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		{% comment %} <div class="col-md-3">
			{% include 'filters.html' %}
		</div> {% endcomment %}
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
            {% if category_products %}
			<div class="row">
                {% for category_product in category_products %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{category_product.slug}}/{{category_product.id}}"><img src="/media/{{category_product.productattribute_set.first.image}}" class="card-img-top" alt="{{category_product.title}}"></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="#">{{category_product.title}}</a></h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
            {% endif %}
			<p class="my-4 text-center"><a href="/products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

main/templates/filters.html
{% comment %} {% load static %}
<script type="text/javascript" src="{% static 'product-filter.js' %}"></script>
    <h3 class="mb-4 border-bottom pb-1">Filters</h3>
    <!-- Filter 1 -->
    <div class="card mb-4">
        <h6 class="card-header">Colors</h6>
        <div class="list-group list-group-flush">
            {% for color in colors %}
            <li class="list-group-item">
                <input class="filter-checkbox" data-filter="color" value="{{color.color__id}}"" type="checkbox" />&nbsp;
                <button class="btn" style="background-color: {{color.color__color_code}}; margin-top: -5px;"></button>
            </li>
            {% endfor %}
        </div>
    </div>
    <!-- Filter 2 -->
    <div class="card mb-4">
        <h6 class="card-header">Categories</h6>
        <div class="list-group list-group-flush">
            {% for category in categories %}
            <li class="list-group-item">
                <input class="filter-checkbox" data-filter="category" type="checkbox" />&nbsp;
                {{category.category__title}}
            </li>
            {% endfor %}
        </div>
    </div>
    <!-- Filter 3 -->
    <div class="card mb-4">
        <h6 class="card-header">Brands</h6>
        <div class="list-group list-group-flush">
            {% for brand in brands %}
            <li class="list-group-item">
                <input class="filter-checkbox" data-filter="brand" type="checkbox" />&nbsp;
                {{brand.brand__title}}
            </li>
            {% endfor %}
        </div>
    </div>
    <!-- Filter 3 -->
    <div class="card mb-4">
        <h6 class="card-header">Sizes</h6>
        <div class="list-group list-group-flush">
            {% for size in sizes %}
            <li class="list-group-item">
                <input class="filter-checkbox" data-filter="size" type="checkbox" />&nbsp;
                {{size.size__title}}
            </li>
            {% endfor %}
        </div>
    </div> {% endcomment %}

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Home Slider -->
<section class="py-5 text-center container">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">Sneaker Heads</h1>
      <p class="fs-5 text-muted">Home for worlds most exclusive sneakers!</p>
    </div>

    <p>
      <a href="#" class="btn btn-primary my-2">All Products</a>
      <a href="#" class="btn btn-primary my-2">Brands</a>
    </p>
    </div>
    </div>
  </section>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <main class="container my-4">
      <!-- Featured Products -->
      <h3 class="my-4 border-bottom pb-1">Featured Products</h3>
      <div class="row">
          {% for featured_product in featured_products %}
          <div class="col-md-3 mb-4">
              <div class="card shadow">
                <a href="/detail.php"><img src="/media/{{featured_product.productattribute_set.first.image}}" class="card-img-top" alt="{{featured_product.image}}"></a>
                <div class="card-body">
                  <h6 class="card-text"><a href="/detail.php">{{featured_product.title}}</a></h6>
                </div>
                <div class="card-footer">
                    <button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
                    <button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
                    <span class="float-right">
                        4.5/5
                        <i class="fa fa-star text-warning"></i>
                    </span>
                </div>
              </div>
          </div>
          {% endfor %}
      </div>
      <p class="my-4 text-center"><a href="{% url 'product-list'%}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
  </main>
{% endblock content %}

main/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">{{product_detail.title}}</h3>
	<div class="row">
		<!-- Images -->
		<div class="col-md-4">
			<img id="zoom_01" data-zoom-image="/media/{{product_detail.productattribute_set.first.image}}" src="/media/{{product_detail.productattribute_set.first.image}}" class="card-img-top" alt="{{product_detail.title}}">
		</div>
		<div class="col-md-8">
			<p>{{product_detail.detail}}</p>
			<hr/>
			<table class="table table-bordered">
				
				<tr>
					<th>Colors</th>
					<td>
                        {% for color in colors %}
						    <button class="btn btn-danger btn-lg choose-color " data-price="{{color.price}}" data-color="{{color.color__id}}" style="background-color: {{color.color__color_code}}"></button>
                        {% endfor %}
                        <tr>
                            <th>Sizes</th>
                            <td>
                                {% for size in sizes %}
                                    <button " class="btn btn-outline-secondary btn-sm choose-size color{{size.color__id}}">{{size.size__title}}</button>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th>Price</th>
                            <th>CAD <span class="product-price">{{product_detail.productattribute_set.first.price}}</span></th>
                        </tr>
						
					</td>
				</tr>
				
			</table>
			<hr/>
			<div class="input-group my-3" style="width:30%;">
			  <input type="number" class="form-control" />
			  <div class="input-group-append">
			    <button class="btn btn-primary btn-sm" type="button" id="button-addon2"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
			  </div>
			</div>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-md-6">
			<h3 class="my-3">Detail</h3>
			<!-- Detail -->
			<table class="table table-bordered">
				<tr>
					<th>Brand</th>
					<td><a href="#">{{product_detail.brand.title}}</a></td>
				</tr>
				<tr>
					<th>Category</th>
					<td><a href="#">{{product_detail.category.title}}</a></td>
				</tr>
				<tr>
					<th>Specification</th>
					<td>{{product_detail.specs}}</td>
				</tr>
			</table>
		</div>
		<!-- Reviews -->
		<div class="col-md-6">
			<h3 class="my-3">Reviews - 4.5/5 <i class="fa fa-star text-warning"></i></h3>
			<div class="card">
				<div class="card-body" style="max-height: 400px; overflow: auto;">
					<!-- Detail -->
					<blockquote class="blockquote text-right">
					  <small>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</small>
					  <footer class="blockquote-footer">User 
					  	<cite title="Source Title">
					  		<i class="fa fa-star text-warning"></i>
					  		<i class="fa fa-star text-warning"></i>
					  		<i class="fa fa-star text-warning"></i>
					  		<i class="fa fa-star text-warning"></i>
					  	</cite>
					  </footer>
					</blockquote>
					<hr />
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
    <!--Related Products-->
    <h3 class="mt-4 mb-3 border-bottom pb-1">Related Products</h3>
    <div class="row">
        {% for related_product in related_products%}
				<div class="col-md-3 mb-4">
                    
					<div class="card shadow">
					    <a href="/product/{{related_product.slug}}/{{related_product.id}}"><img src="/media/{{related_product.productattribute_set.first.image}}" class="card-img-top" alt="{{related_product.title}}"></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="#">{{related_product.title}}</a></h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
    </div>
</main>
<script src="https://cdn.jsdelivr.net/gh/igorlino/elevatezoom-plus@1.2.3/src/jquery.ez-plus.js"></script>
<script>
    $('#zoom_01').ezPlus();
</script>
{% endblock content %}

main/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		{% comment %} <div class="col-md-3">
			{% include 'filters.html' %}
		</div > {% endcomment %}
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
            {% if products %}
			<div class="row" id="filteredProducts">
                {% for product in products%}
				<div class="col product-box">
					<div class="card shadow-sm">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="#">{{product.title}}</a></h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
            {% endif %}
			<p class="my-4 text-center"><button id="loadMore" product-total="{{total_products}}" product-limit="3" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
<script type="text/javascript" src="{% static 'custom.js' %}"></script>
{% endblock %}

main/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main class="container my-4">
      <!-- Featured Products -->
      <h3 class="my-4 border-bottom pb-1"><span class="text-muted">Search Result for {{request.GET.q}}</span></h3>
      <div class="row">
          {% for featured_product in featured_products %}
          <div class="col-md-3 mb-4">
              <div class="card shadow">
                <a href="/detail.php"><img src="/media/{{featured_product.productattribute_set.first.image}}" class="card-img-top" alt="{{featured_product.image}}"></a>
                <div class="card-body">
                  <h6 class="card-text"><a href="/detail.php">{{featured_product.title}}</a></h6>
                </div>
                <div class="card-footer">
                    <button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
                    <button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
                    <span class="float-right">
                        4.5/5
                        <i class="fa fa-star text-warning"></i>
                    </span>
                </div>
              </div>
          </div>
          {% endfor %}
      </div>
      <p class="my-4 text-center"><a href="{% url 'product-list'%}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
  </main>
{% endblock content %}